openapi: "3.0.1"
info:
  title: "PeTaL API Documentation"
  version: "v7"
servers:
- url: "https://unbqm6hov8.execute-api.us-east-2.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: "v1"
paths:
  /getarticles:
    get:
      tags:
      - "API methods"
      summary: "Finds articles by label"
      description: "Find articles with the level3 label supplied."
      parameters:
      - name: "level3"
        in: "query"
        description: "Label supplied should be all lowercase, with spaces converted\
          \ to underscores."
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "successful operation"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
  /getalllabels:
    get:
      tags:
      - "API methods"
      summary: "Get all labels"
      responses:
        "200":
          description: "successful operation"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
components:
  schemas:
    Empty:
      title: "Empty Schema"
      type: "object"